### ISSUE TITLE
Bug/iip 7 push resets nonce

### ISSUE THREAD

**Issue by nbundi** [fiatdao/delphi-ii#27]
push resets the proposal nonce to 0

https://github.com/fiatdao/delphi-ii/blob/74fdb19ce126ec5dd074b747346986c4a208fccd/src/OptimisticChainlinkOracle.sol#L217

therefore, after a push new proposals with arbitrarily old values (roundTimestamp) can be created

https://github.com/fiatdao/delphi-ii/blob/74fdb19ce126ec5dd074b747346986c4a208fccd/src/OptimisticOracle.sol#L162

better set nonce to the Chainlink feed's latestRoundData roundTimestamp so after a push new proposals have to be newer than the latestRoundData

**Comment by amarcu** [comment]
This is an issue with all initial shifts (post `registerRate()` and post `push()`). For the bb-a-USD oracle I added a fix where in push we add the roundTimestamp to the nonce that is used to overwrite the current proposal, this allows us to check in `encodeNonce()` that the proposed value is newer than what was set in `push()` and also allows us to skip updating **target** in `shift()` because the previous value for a push is 0. If this solution is accepted I can also apply it to the simple ChainlinkOracle.

**Comment by amarcu** [comment]
This only fixes the `push()` issue, for the initial shift we could run a push on `activateRateId` instead of creating the blank proposal that we use now.

**Comment by elnilz** [comment]
it lgtm wdyt @SolcAndMe ?

**Comment by amarcu** [comment]
fixed included in https://github.com/fiatdao/delphi-ii/pull/26
